name: Release Steel Control

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Garantir dependências limpas
        run: go mod tidy

      - name: Build Steel Control
        run: |
          go build -ldflags="-s -w -H windowsgui" -o Produtividade.exe main.go

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: Produtividade.exe
